### ISSUE TITLE
NOT ANY LINK TO USE THE FUNCTION IT SAYS?

### ISSUE THREAD

**Issue by sebastian7pardo** [maxfire2008/spotify-video#1]
ANY WEB PAGE OR APP FOR SPOTIFY VIDEO?? NO LINK

**Comment by maxfire2008** [comment]
This project is currently a work in progress - I expect it will be done in a month or so

**Comment by maxfire2008** [comment]
@sebastian7pardo It's now in a working-ish state. You'll need to have a tiny bit of Python knowledge to use it
